server:
  port: 8081
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

spring:
  application:
    name: ms-customer
  cloud:
    aws:
      credentials:
        access-key: ${makersweb.aws.access-key}
        secret-key: ${makersweb.aws.secret-key}
        instance-profile: true
      endpoint: ${makersweb.aws.endpoint}
      region:
        static: ${makersweb.aws.region}
  datasource:
    url: jdbc:mysql://${mysql.url}/${mysql.schema}?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${mysql.username}
    password: ${mysql.password}
    hikari:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 600000
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: master
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        generate_statistics: false
        connection:
          autocommit: true
    database-platform: org.hibernate.dialect.MySQLDialect
  jackson:
    default-property-inclusion: non_null
    deserialization:
      read-unknown-enum-values-as-null: true
    serialization:
      write-dates-as-timestamps: true

