mysql:
  username: root
  password: Salmos89!
  schema: makersdb
  url: localhost:3307

makersweb:
  aws:
    access-key: localstackKeyId
    secret-key: Tulipa89!
    endpoint: http://localhost:4566
    region: ${AWS_REGION:us-east-1}
    sqs:
      customer-service:
        queue: customerServiceQueue
      notification-return:
        queue: notificationReturnQueue
