version: '3.8'

services:

  order-db:
    image: mongo:latest
    container_name: order-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=salmos89
    volumes:
      - "./.docker/data/mongo:/data/db"
    networks:
      - orchestrator-saga

  product-db:
    image: postgres:latest
    container_name: product-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=product-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "./.docker/data/productdb:/var/lib/postgresql/data"
    networks:
      - orchestrator-saga

  payment-db:
    image: postgres:latest
    container_name: payment-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=payment-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "./.docker/data/paymentdb:/var/lib/postgresql/data"
    networks:
      - orchestrator-saga

  inventory-db:
    image: postgres:latest
    container_name: inventory-db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=inventory-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "./.docker/data/inventorydb:/var/lib/postgresql/data"
    networks:
      - orchestrator-saga

  kafka:
    container_name: kafka
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    networks:
      - orchestrator-saga
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
    volumes:
      - "./.docker/data/kafka/data:/var/lib/kafka/data"

  redpanda-console:
    container_name: redpanda
    image: docker.redpanda.com/vectorized/console:latest
    restart: on-failure
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    ports:
      - "8081:8080"
    networks:
      - orchestrator-saga
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["kafka:29092"]
    depends_on:
      - "kafka"

  order-service:
    build: './order-service'
    container_name: order-service
    environment:
      - KAFKA_BROKER=kafka:29092
      - MONGO_DB_URI=mongodb://admin:123456@order-db:27017
    ports:
      - "3000:3000"
    depends_on:
      - "order-db"
      - "kafka"
    networks:
      - orchestrator-saga

  orchestrator-service:
    build: './orchestrator-service'
    container_name: orchestrator-service
    environment:
      - KAFKA_BROKER=kafka:29092
    ports:
      - "8080:8080"
    depends_on:
      - "kafka"
    networks:
      - orchestrator-saga

  product-validation-service:
    build: './product-validation-service'
    container_name: product-validation-service
    environment:
      - KAFKA_BROKER=kafka:29092
      - DB_HOST=product-db
      - DB_PORT=5432
      - DB_NAME=product-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8090:8090"
    depends_on:
      - "product-db"
      - "kafka"
    networks:
      - orchestrator-saga

  payment-service:
    build: './payment-service'
    container_name: payment-service
    environment:
      - KAFKA_BROKER=kafka:29092
      - DB_HOST=payment-db
      - DB_PORT=5432
      - DB_NAME=payment-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8091:8091"
    depends_on:
      - "payment-db"
      - "kafka"
    networks:
      - orchestrator-saga

  inventory-service:
    build: './inventory-service'
    container_name: inventory-service
    environment:
      - KAFKA_BROKER=kafka:29092
      - DB_HOST=inventory-db
      - DB_PORT=5432
      - DB_NAME=inventory-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8092:8092"
    depends_on:
      - "inventory-db"
      - "kafka"
    networks:
      - orchestrator-saga

networks:
  orchestrator-saga:
    driver: bridge